### PR TITLE
Add randomized C++ solution

### PR DESCRIPTION
**Pull request by cherrry**
Make use of randomized algorithm learnt from the algorithm course.
It returns the first solution quite fast.

Before optimization:

```
$ time ./abcdefghppp
85 - 46 = 39, 39 + 72 = 111
./abcdefghppp  0.22s user 0.00s system 99% cpu 0.221 total
```
#### Edited

After optimization:

```
$ time ./abcdefghppp
85 - 46 = 39, 39 + 72 = 111
./abcdefghppp  0.00s user 0.00s system 64% cpu 0.003 total
```

The performance improved A LOT!

### CODE REVIEW

**Comment by gaplo917** [comment]
But my scala optimized solution only take 2ms (JMH Benchmark) for all solution :laughing: 

p.s  Macbook pro retina 15" 2012

**Comment by cherrry** [comment]
ok, let me optimize my code

**Comment by cherrry** [comment]
My optimized algorithm takes no time now, please kindly review again :joy:

**Comment by gaplo917** [comment]
Similar problem #25

**Pull request closed without merging**
