### PR TITLE
fast generative search algorithm 

### PR DESCRIPTION
**Pull request by jackhftang**
removed the old one.

### CODE REVIEW

**Comment by gaplo917** [comment]
ops, your formula will become different according to the base. 

 I think it will be more consistent if we play a SAME formula with different base.

do you agree?

**Comment by jackhftang** [comment]
The general form or our problem is ABCDEFGHPPP(base, width) And what you want to do is to separate it into two specific sub-problems with fixed width (width mean that number digit for each number, same as you call formula).
1. AdvanceBase(base) = ABCDEFGHPPP(base,2)
2. AdvanceFormula(base) = ABCDEFGHPPP(base,4)
the min and max bound for width are 1 and floor( (base-1)/4 ).  And my solution always choose the max value of width. Well, I am not sure, but there could be some interesting things for choosing the width value between min and max. 

In similar way, you can separate ABCDEFGHPPP into more forms. e.g. 
AdvanceXXX(base) = ABCDEFGHPPP(base,6)
AdvanceYYY(base) = ABCDEFGHPPP(base,7)
...
(FYI, for base 21, the width = 5 is solvable in reasonable time, though you may argue that width cannot possible grow arbitrarily.) 
You will have management problem then... And also, it is possible that one algorithm can handle various base and width. Should developers submit the same code with hard-coded width for each AdvanceXXX?

IMO, one way to solve is to ask each (advanced) submission to include a run.sh which you can call ./run.sh <base> <width> and output the formula in specific format and order. And then, you can have an automatic verifier and benchmark. But you need to enforce an environment e.g. linux window (but whatever choices you choose will make some people inconvenient). And also there are too many languages... need efforts to setup environments and sandbox (if you care security). 

No optimal solution. see if others have other idea.

**Comment by gaplo917** [comment]
That's why I separate two directory. 
- Advance-base ( original formula* with different base )
- Advance-formula ( new formula** with different base )

\* AB - CD = EF , EF + GH = PPP
** ABCD - EFGH = IJKL, IJKL + MNOP = QQQQQ

I think most of the brute force code can't handle base = 16 with * , because it has more than 10^6 iteration compared to base 10. 

Btw, Have you tested your code with base 21 & ** formula ( `width = 4` ) ?  

By my understanding, it should be more challenging than using formula ( `width = 5` ) with base 21

**Comment by jackhftang** [comment]
just tested on macbook pro 2014. wXbY = width of X, and base-Y
w4b21: 1595019 solutions, took ~8s 
w5b21: 96220 solutions, took ~3.15s 
w3b21: 374544 solution, take ~1.5s
w2b21: 12856 solution, took <1s
(exclude IO time)
Well, w4b21 is more challenging than w5b21 in term of runtime, but the point is what is the special of 4? 
You can also test with width of 3.

**Comment by gaplo917** [comment]
:laughing: `width = 4` Reason: Not scientific -  Just a double of the parameter

**Comment by gaplo917** [comment]
But the `Base` level jumping are in constant interval to test where the computational time is also constantly increase.

**Comment by jackhftang** [comment]
So, back to the original question, I should make two copys of code with one width=2 and the other width=4?

**Comment by gaplo917** [comment]
Refined the Advance structure as we discuss, Please make corresponding amendment ! Thanks

**Comment by jackhftang** [comment]
can merge now.

**Comment by jackhftang** [comment]
sorry, the file structure seems changed from last time I saw..

**Comment by gaplo917** [comment]
@jackhftang Yes, only one `Advance` Folder

**Comment by jackhftang** [comment]
okay now

**Comment by gaplo917** [comment]
可以撿撿個 Readme

**Pull request merged**
