### PR TITLE
Added solver to an advanced problem: python-permutation-bruteforce-parallel

### PR DESCRIPTION
**Pull request by Saren-Arterius**

### CODE REVIEW

**Comment by gaplo917** [comment]
output.txt must be included under Advance directory :) 

Please read the README.md to see what information must be included in the output.txt

**Comment by Saren-Arterius** [comment]
That's troublesome to do.

**Comment by gaplo917** [comment]
I agree. but output.txt (run in the same machine) is very useful for others to analyze your probelm without running it

Please consider to PR again. Your works & explainations are clean & clear.

**Comment by Saren-Arterius** [comment]
聽日冇咁眼訓先

**Comment by gaplo917** [comment]
早抖 :sleeping:

**Pull request closed without merging**
