### PR TITLE
High perf python implementation

### PR DESCRIPTION
**Pull request by Saren-Arterius**

### CODE REVIEW

**Comment by gaplo917** [comment]
Sorry, please follow the current folder structure for consistency 

You may name it `python-high-perf/abcdefghppp.py`  Or other meaningful name

**Comment by Saren-Arterius** [comment]
Commit revised, please take a look.

**Comment by gaplo917** [comment]
Please rebase & squash to single commit 

Similar case
https://github.com/mingchuno/ABCDEFGHPPP/pull/24

**Comment by Saren-Arterius** [comment]
Never used `git rebase`, but is that really necessary?

**Comment by gaplo917** [comment]
`Create abcdefghppp_high_perf.py`
`Delete abcdefghppp_high_perf.py`

which are redundant commit, if I merged to master, the master git history will also show this two redundant commit

So, you should rewrite your own git history ( 3 commit meld into 1 commit )

**Comment by Saren-Arterius** [comment]
k

**Comment by Saren-Arterius** [comment]
Commit revised, please take a look.

**Comment by Saren-Arterius** [comment]
Thank you very much.

**Pull request merged**
