### PR TITLE
Added php-2-for-loop

### PR DESCRIPTION
**Pull request by lmsam**
Added php solution with 2 for loop only

### CODE REVIEW

**Comment by gaplo917** [comment]
Please rebase and squash into single commit.

**Comment by lmsam** [comment]
Sorry, I am not sure how to do it.... can you tell me?

**Comment by gaplo917** [comment]
First you have to check your commit history

```
git log 
```

Find a commit hash BEFORE ONE commit of "Add PHP code", Copy the commit hash i.e. `abcab12a13eacbeabe1` 

Then assume you get the commit hash `abcab12a13eacbeabe1`, type this

```
git rebase -i abcab12a13eacbeabe1
```

You should see something like this

```
pick xxxx Add PHP code
pick xxxx update folder name to php-2-for-loop
....
```

Change all the `pick` to `squash` except the first line &  save the result ( :wq if you use vim/vi )

You will ask for edit the commit message, feel free to edit & save the result.

Then your commits should be merge into one single commit.

At last, you MUST force push to rewrite your git history.

```
git push -f master
```

**Comment by lmsam** [comment]
Done, please see is it ok now, thanks

**Comment by gaplo917** [comment]
Find a commit hash **BEFORE ONE** commit of "Add PHP code" 😂.  

Currently your PR is still two commit .

**Comment by lmsam** [comment]
Haha, should be ok now, thanks

**Pull request merged**
