### PR TITLE
Spark with Python API

### PR DESCRIPTION
**Pull request by jethrolam**

### CODE REVIEW

**Comment by gaplo917** [comment]
Normally, solution with leading zero of two digit number shouldn't regards as anwser.

Please fix and consider to rebase & squash your commits to single commit

**Comment by jethrolam** [comment]
Hmm can you explain why "57-09=48, 48+63=111" is not considered a solution?  

(e.g. the wordings in the original question say no 0's?)

**Comment by gaplo917** [comment]
I think most of the Strong typed language is not allow an integer with leading zero, it will trigger compile error.

Also I think you can't  found any use case of mathematics that use 09 to represent 9, which is trivial to do so

**Comment by jethrolam** [comment]
No problem.  Ready again.

**Comment by gaplo917** [comment]
Thanks for the constribution. 

As Spark is a nice tools supports different language, would you mind to rename it to python-spark-permutation/abcdefgppp.py?  Or other meaningful names are welcome

**Comment by jethrolam** [comment]
Spark is a computing engine written in Scala, which I invoke it using python interface. To be technically correct it should not be viewed as another python application.   It looks like python language but under the hood it is running Scala. 

I renamed it to spark-python-smartbruteforce... is it ok?

**Pull request merged**
