### PR TITLE
fix c++ typo and add javascript solvers

### PR DESCRIPTION
**Pull request by jackhftang**
- fix c++ typo (which I think it is reasonable to separate as two commits)
- add three javascript solvers
  - an reimplementation of nextPermutation in pure javascript
  - named 1-loop as suggested (but there are loops in check anyway)
  - an generic one and readMe.md

### CODE REVIEW

**Comment by gaplo917** [comment]
your commit included 

`javascript/abcdefghppp2.js`

please remove it and 

git commit --amend

**Comment by jackhftang** [comment]
I know ar, but I consider abcdefghppp.js and abcdefghppp2.js as two implementations. 
You may think that nextPermutation is not an interesting/new implementation, but unlike the permutation() in abcdefghppp.js (which look tricky to me), it generates and store all permutation and all its intermediate list (see the use of filter and concat) in memory as list. This implementation is actually very memory hungry (and a lot of quick gc) and not so efficient (it should some be somehow 2N to 3N for each permutation). Comparing to the implementation in abcdefghppp2.js, which use constant space and the algorithm allow early break in each next permutation, which in amortized sense should be somehow N. 

Well, and I am not sure whether to remove/modify others' accepted effort.

**Comment by gaplo917** [comment]
The javascript version is one of my contribution. 

As you said, it consume a lot of memory by generating the permutation list. Maybe I would change it to use generator approach ( ES6 features) and I will rename it to javascript-es6-generator/abcdefghppp.js

As I see, you didn't use any ES6 features. Would u mind to rename it to javascript-es5/abcdefghppp.js

Or any meaningful name is welcome. We hope to keep a consistent folder struture ( 1 folder includes 1 source code , output, README.md). Hope you understand

**Comment by jackhftang** [comment]
sorry.. I mistakenly overrided the file, which I am not aware of...

**Pull request closed without merging**
