### PR TITLE
JS version of calculation

### PR DESCRIPTION
**Pull request by nodegin**

### CODE REVIEW

**Comment by jackhftang** [comment]
well, what are you doing @@?

**Comment by nodegin** [comment]
@jackhftang no idea what the fuck i just wrote

**Comment by nodegin** [comment]
If AB CD GH is two digit number, therefore P must be 1?
Correct me if I was wrong..

**Comment by jackhftang** [comment]
Yes, you are right. Given ab - cd = ef && ef + gh = ppp 
It is obvious that 
ef + gh < 200 => ppp = 000 or 111 
if p = 0, then ef = gh = 00, not possible 
so p = 1

**Comment by nodegin** [comment]
so could my code be called a solution? lol

**Comment by jackhftang** [comment]
we want all solutions, but you just give one =]

**Comment by gaplo917** [comment]
Hi @nodegin,  could you write a README.md and briefly explain / prove why your solution is working to find one of the solution :smile:

**Comment by nodegin** [comment]
I saw my code doesn't match the question, closing PR

**Pull request closed without merging**
