### PR TITLE
Added python-random

### PR DESCRIPTION
**Pull request by circlehk**
pure wild guess
straight forward logic, short code, not-too-bad speed :)

### CODE REVIEW

**Comment by gaplo917** [comment]
IMHO, random shouldn't implement in this way.

For example, if someone give you a problem that is no solution, you program will infinity loop & dead.

Try to think about how to avoid infinite loop although using random approach :smile: .

**Comment by circlehk** [comment]
you are absolutely right but it was implemented like that on purpose
that's what meant by wild guessing... :stuck_out_tongue:

fact is that this problem has known solutions... this program behaves just like how normal human make "wild" guesses (not educated ones) - we probably can't remember all trials we did... 

i executed this for 10,000 times...
- the average time to get 1 correct  answer is only 0.7s (max 6.795s) on a not-too-new PC...
- in average every 5.47 consecutive ans would cover all the 3 solutions, and even in worst case it only took 24 consecutive correct solutions to cover all.

surprisingly efficient & effective, isn't it? :stuck_out_tongue_closed_eyes: 

anyway, this is purely for fun... :see_no_evil:

**Comment by gaplo917** [comment]
IMHO, the solution contains "bug", buy you can fix it by doing the followings:
- You can first generate a List of permutation results 
- **RANDOMLY** consume the permutation results

:laughing:

**Comment by circlehk** [comment]
i don't really prefer any kinds of pre-generation cause it violates the purpose of random wild-guessing :laughing: 

if the concern here is infinite loop, how about adding exit conditions, e.g. a timeout, or max of of trials?

**Comment by cherrry** [comment]
I don't think @circlehk need to change his code except adding a max no of trials
Precompute and hardcode is another art, like #21

**Comment by gaplo917** [comment]
@mingchuno To see if you agree to timeout/MAX_RETRY approach.

**Comment by circlehk** [comment]
Added timeout, default 5 second
:laughing::laughing::laughing:

**Comment by mingchuno** [comment]
nice!

**Pull request merged**
